id: P4A439A91
initial_creation_type: input
source_metadata:
  title: Jigme Lingpa Series
  language: pt
  description: A series of texts by and about the great Dzogchen master Rigdzin Jigme
    Lingpa (rig 'dzin 'jigs med gling pa, 1730–1798), who revealed the Longchen Nyingtik
    (klong chen snying thig) collection.
  volume:
    97438629ce6c4d6e8d16efd1ae711ed8:
      title: An Aspiration for the Final Age
      parent: Aspiration Prayers
    be621920940545d288a9e71c74669516:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers
    c8aba62ce1c449f98190182adaa09660:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: Aspiration Prayers
    dc7dcbc1e8a3478a8857a58624bc4625:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Aspiration Prayers
    7445495527c9488daf5d1b3af92edb3d:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Aspiration Prayers
    2787fb0d755745cea8991ff0e78ea016:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Catalogues
    b69f33f8453c4f91a3e49a1b1e927ca4:
      title: 'Elucidating the Body Maṇḍala: Clarifications on the Recitation Manual
        of the Female Practice of the Queen of Great Bliss'
      parent: Commentaries
    b804b7aec2794ea882658d3a69602e32:
      title: Main Recitation Manual for the Female Practice of the Queen of Great
        Bliss
      parent: Commentaries
    2bb90461f9ff457ebb9ba61610026aab:
      title: 'The Casket of Siddhis: A Recitation Manual for “Vidyādhara Assembly”
        (Rigdzin Düpa)'
      parent: Commentaries
    157ea53ea0ed4fa3b93fbc4ac552c925:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Commentaries
    88fdce574a7546489780a23c7d04268d:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Commentaries
    d705ba0b7dab4d3c9b770f731f944eed:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Confession
    9067744f34d644b49461107d17b43c17:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Dharma Protectors
    afa32b15345946bd9f9ee3c1d24c28f1:
      title: Vajra Verses on the Natural State
      parent: Dzogchen
    0e5aeb954a4c41a08d0652421c4783ed:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Empowerment Rites
    0c37de11c7344fdcaa95948b6c27c131:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Empowerment Rites
    0d75f1794bbb41fbb086e231fa118fda:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Empowerment Rites
    0fcfae32bb96420fa5cde214117a5fda:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Guru Rinpoche Prayers
    5ec7b014bf5043bc9e8b562619f3fa55:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Guru Rinpoche Prayers
    0ca2b8b1a90c464d962d405fe0bead32:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Guru Rinpoche Prayers
    30f428b65ae5495cbd9243afd6665d0b:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    f526f772ae9f4ad481c84cc7eb683ea0:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Guru Rinpoche Prayers
    e60a2a21689d4980875fbf2dc4ac66f5:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Guru Yoga
    41d10c40155f49b7b8528d7f66612406:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Guru Yoga
    e9b8c2aaa5534b2292b219d291281cb2:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: History
    ede9bed9f60547618914b3731c05841d:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    f957f618c24541c9a44905674b144b0a:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Lineage Prayers
    c6bcd9f8dd414277983d8b9410249f5b:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Longchen Nyingtik
    3852d671e48045b3a3e932e2d1560c4c:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    3f0faa449ded4857a0318acafc3faad3:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Pilgrimage
    24f166da53414064a32c3012abea3f94:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    a1562231f57f4aefb5ca0032e52c0da7:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Practices
    43ef943d351948728b630bea496a37f3:
      title: Descent of Blessings of the Eight Vidyādharas
      parent: Practices
    e659194352ea4d20a251299493863002:
      title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
      parent: Practices
    88910f09e72746599a861d4369c4d43b:
      title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female
        Awareness-Holder (Yumka)'
      parent: Practices
    fd784794f2164312bdd0d6f7a761dd21:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      parent: Practices
    4ad9c4e4460544128630213f44db2afb:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Practices
    78ea0af7ad8f4c56bb7c081915e824b3:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Practices
    e3297319b39440d2b59844343e741f44:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Practices
    3618ff9209e242ac895dee7a1697fbc9:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Praise
    0e682f8d5669404c991be07f7c778321:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Praise
    d74beedf6c11477b95bf94bfdd61e555:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    1e1f461889f241d5b3e4132bdfa2925b:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Prayers
    b5b5c21660b5422b8c145b4e7aa1af64:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Prayers
    bddb4a5f2fac424badbe73665beb81ba:
      title: 'Devotion that Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
      parent: Prayers
    4631d0a5414a4535a2d9f0cff0c40ade:
      title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
      parent: Prayers
    c5ad2ce11bc14b6d82f6af6e29ab94ba:
      title: Prayer to the Garland of Rebirths of the Dzogchenpas of Eastern Tibet
      parent: Prayers
    9d8b4423508f48bba0c03ae87524d00a:
      title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
      parent: Prayers
    ca5b4b168dc1461f8473cdb1bcdd522e:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Prayers
    c1e86a98d0c447c69b108100066dc8cd:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Sādhanas
    823a204035f041af8b77e90e2af0e96a:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    a2f6e6ce35564bbdb97f52421edd17eb:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Sādhanas
    bd50c86d6afd4b27a28461af96064759:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Sādhanas
    d5a9a42ec7614b408939682e9864f474:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Sādhanas
    c1f63b84e0254e9bbc4c15bc0fd976e9:
      title: Sādhana of the Great Master Vairotsana
      parent: Sādhanas
    2cf9c899e7b742d189a1156db914a84f:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Sādhanas
    e4abe2c0470047a8aa85a32fdd4a2540:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Sādhanas
    11617875e4874f94b9c6a6a0855359f3:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Transference (Phowa)
    75a17b770a974ec88528f294d3c38131:
      title: Brief Prayer of the Feast Gathering
      parent: Tsok
    f4c2a5c4d16c4ac581a1aef88be37c93:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Tsok
    6faf863e5eff405bb8c760f4ae5bc2ed:
      title: Song of the Feast (Tsok Lu)
      parent: Tsok
    6ab72dd8a21d4a279f170793d9c0453e:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Calling the Guru from Afar
created_at: '2022-03-01T00:07:12.492802'
last_modified_at: '2022-03-01T00:07:12.492805'
